version: "3"
services:
    website:
        image: php:apache
        depends_on: 
            - api
        volumes: 
            - ./website:/var/www/html
        ports: 
            - "3000:80"
        environment:
            DATABASE_USER: Pozo
            DATABASE_PASSWORD: pozopass
    api:
        build: ./simple_api
        volumes:
            - ./simple_api:/usr/src/app
        ports:
            - "5000:80"


